config/routes.rb
Rails.application.routes.draw do
  resources :practice_data

  root "data_sets#index"

  resources :data_sets do
    collection do
      post :import   # import action on DataSetsController
    end
  end

  resources :row_items

end

app/models/data_set.rb
class DataSet < ActiveRecord::Base
  has_many :row_items, dependent: :destroy

  def self.import(file)
    file_data = CSV.read(file.path, {converters: :numeric})
    data_set = self.make_headline(file_data[0], self.sanitize(file.path.to_s))
    self.make_row_items(data_set, file_data[1..-1])
    data_set
  end

  def self.make_headline(row, title)
    self.clean_array!(row)
    DataSet.create!(title: title,
                    id_title: row[0], x_title: row[1],
                    y_title: row[2], z_title: row[3])
  end

  def chart_data
    self.row_items.as_json(only: [:id_text, :x_data, :y_data, :z_data])
  end

  private

  def self.make_row_items(data_set, rows)
      rows.each do |row|
        self.clean_array!(row)
        data_set.row_items.create!(id_text: row[0], x_data: row[1],
                                y_data: row[2], z_data: row[3])
      end
      return true
  end

  def self.clean_array!(array)
    array.each do |e|
      self.clean_string!(e) if e.class == String
    end
  end

  def self.sanitize(filename)
    filename.sub!(/\A.*(\\|\/)/, "")
    self.clean_string!(filename)
  end

  def self.clean_string!(string)
    if string.class == String
      string.strip!
      string.gsub!(/[^\w\.\-]/,"")
    end
    string
  end

end

app/models/practice_datum.rb
class PracticeDatum < ActiveRecord::Base

  def self.chart_data
    self.all.as_json(only: [:practice, :month, :count, :value])
  end

end

app/models/row_item.rb
class RowItem < ActiveRecord::Base
  belongs_to :data_set
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  before_action :set_data_set, only: [:show, :edit, :update, :destroy]

  # GET /data_sets
  # GET /data_sets.json
  def index
    @data_sets = DataSet.all
  end

  # GET /data_sets/1
  # GET /data_sets/1.json
  def show
  end

  # GET /data_sets/new
  def new
    @data_set = DataSet.new
  end

  # GET /data_sets/1/edit
  def edit
  end

  # POST /data_sets
  # POST /data_sets.json
  def create
    @data_set = DataSet.new(data_set_params)

    respond_to do |format|
      if @data_set.save
        format.html { redirect_to @data_set, notice: 'Data set was successfully created.' }
        format.json { render :show, status: :created, location: @data_set }
      else
        format.html { render :new }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_sets/1
  # PATCH/PUT /data_sets/1.json
  def update
    respond_to do |format|
      if @data_set.update(data_set_params)
        format.html { redirect_to @data_set, notice: 'Data set was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_set }
      else
        format.html { render :edit }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sets/1
  # DELETE /data_sets/1.json
  def destroy
    @data_set.destroy
    respond_to do |format|
      format.html { redirect_to data_sets_url, notice: 'Data set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    DataSet.import(params[:file])
    redirect_to root_url, notice: "Data Imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_set
      @data_set = DataSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_set_params
      params.require(:data_set).permit(:title, :id_title, :x_title, :y_title, :z_title)
    end
end

app/controllers/practice_data_controller.rb
class PracticeDataController < ApplicationController
  before_action :set_practice_datum, only: [:show, :edit, :update, :destroy]

  # GET /practice_data
  # GET /practice_data.json
  def index
    @practice_data = PracticeDatum.all.order(month: :asc, practice: :asc)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practice_data }
    end
  end

  # GET /practice_data/1
  # GET /practice_data/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @practice_datum }
    end
  end

  # GET /practice_data/new
  def new
    @practice_datum = PracticeDatum.new
  end

  # GET /practice_data/1/edit
  def edit
  end

  # POST /practice_data
  # POST /practice_data.json
  def create
    @practice_datum = PracticeDatum.new(practice_datum_params)

    respond_to do |format|
      if @practice_datum.save
        format.html { redirect_to @practice_datum, notice: 'Practice datum was successfully created.' }
        format.json { render json: @practice_datum, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @practice_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practice_data/1
  # PATCH/PUT /practice_data/1.json
  def update
    respond_to do |format|
      if @practice_datum.update(practice_datum_params)
        format.html { redirect_to @practice_datum, notice: 'Practice datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @practice_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practice_data/1
  # DELETE /practice_data/1.json
  def destroy
    @practice_datum.destroy
    respond_to do |format|
      format.html { redirect_to practice_data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice_datum
      @practice_datum = PracticeDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_datum_params
      params.require(:practice_datum).permit(:practice, :month, :count, :value)
    end
end

app/controllers/row_items_controller.rb
class RowItemsController < ApplicationController
  before_action :set_row_item, only: [:show, :edit, :update, :destroy]

  # GET /row_items
  # GET /row_items.json
  def index
    @row_items = RowItem.all
  end

  # GET /row_items/1
  # GET /row_items/1.json
  def show
  end

  # GET /row_items/new
  def new
    @row_item = RowItem.new
  end

  # GET /row_items/1/edit
  def edit
  end

  # POST /row_items
  # POST /row_items.json
  def create
    @row_item = RowItem.new(row_item_params)

    respond_to do |format|
      if @row_item.save
        format.html { redirect_to @row_item, notice: 'Row item was successfully created.' }
        format.json { render :show, status: :created, location: @row_item }
      else
        format.html { render :new }
        format.json { render json: @row_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /row_items/1
  # PATCH/PUT /row_items/1.json
  def update
    respond_to do |format|
      if @row_item.update(row_item_params)
        format.html { redirect_to @row_item, notice: 'Row item was successfully updated.' }
        format.json { render :show, status: :ok, location: @row_item }
      else
        format.html { render :edit }
        format.json { render json: @row_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /row_items/1
  # DELETE /row_items/1.json
  def destroy
    @row_item.destroy
    respond_to do |format|
      format.html { redirect_to row_items_url, notice: 'Row item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_row_item
      @row_item = RowItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def row_item_params
      params.require(:row_item).permit(:id_text, :x_data, :y_data, :z_data, :data_set_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_sets_helper.rb
module DataSetsHelper
end

app/helpers/practice_data_helper.rb
module PracticeDataHelper
end

app/helpers/row_items_helper.rb
module RowItemsHelper
end

app/views/data_sets/_form.html.erb
<%= form_for(@data_set) do |f| %>
  <% if @data_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_set.errors.count, "error") %> prohibited this data_set from being saved:</h2>

      <ul>
      <% @data_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :id_title %><br>
    <%= f.text_field :id_title %>
  </div>
  <div class="field">
    <%= f.label :x_title %><br>
    <%= f.text_field :x_title %>
  </div>
  <div class="field">
    <%= f.label :y_title %><br>
    <%= f.text_field :y_title %>
  </div>
  <div class="field">
    <%= f.label :z_title %><br>
    <%= f.text_field :z_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_sets/edit.html.erb
<h1>Editing data_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_set %> |
<%= link_to 'Back', data_sets_path %>

app/views/data_sets/index.html.erb
<h1>Data Sets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Id title</th>
      <th>X title</th>
      <th>Y title</th>
      <th>Radius title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_sets.each do |data_set| %>
      <tr>
        <td><%= data_set.title %></td>
        <td><%= data_set.id_title %></td>
        <td><%= data_set.x_title %></td>
        <td><%= data_set.y_title %></td>
        <td><%= data_set.z_title %></td>
        <td><%= link_to 'Show', data_set %></td>
        <td><%= link_to 'Edit', edit_data_set_path(data_set) %></td>
        <td><%= link_to 'Destroy', data_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Import Data</h2>
<%= form_tag import_data_sets_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload CSV" %>
<% end %>


<h2>Other Projects</h2>
<%= link_to 'Pie Charts', practice_data_path %>

app/views/data_sets/new.html.erb
<h1>New data_set</h1>

<%= render 'form' %>

<%= link_to 'Back', data_sets_path %>

app/views/data_sets/show.html.erb
<p id="notice"><%= notice %></th>

<h1> <%= @data_set.title %> </h1>

<%= content_tag(:div, "", id: "quadrant_data", data: {items: @data_set.chart_data }) %>

<table>
  <thead>
    <tr>
      <th> <%= @data_set.id_title %> </th>
      <th> <%= @data_set.x_title %> </th>
      <th> <%= @data_set.y_title %> </th>
      <th> <%= @data_set.z_title %> </th>
    </tr>
  </thead>

  <tbody>
  <% @data_set.row_items.each do |row| %>
    <tr>
      <td> <%= row.id_text %> </td>
      <td> <%= row.x_data %> </td>
      <td> <%= row.y_data %> </td>
      <td> <%= row.z_data %> </td>
    </tr>
  </tbody>
  <% end %>
</table>

<%= link_to 'Edit', edit_data_set_path(@data_set) %> |
<%= link_to 'Back', data_sets_path %>

<% javascript_include_tag "data_set_chart" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quadrant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<%= yield %>

</body>
</html>

app/views/practice_data/_form.html.erb
<%= form_for(@practice_datum) do |f| %>
  <% if @practice_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice_datum.errors.count, "error") %> prohibited this practice_datum from being saved:</h2>

      <ul>
      <% @practice_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :practice %><br>
    <%= f.text_field :practice %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practice_data/edit.html.erb
<h1>Editing practice_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice_datum %> |
<%= link_to 'Back', practice_data_path %>

app/views/practice_data/index.html.erb
<h1>Practice Data</h1>

<select name="test" id ="month_selector">
  <%= options_for_select(PracticeDatum.chart_data.map{ |e| [e["month"].to_s, e["month"]]}.uniq.sort, 2 ) %>
</select>

<%= content_tag(:div, "", id: "key-array", data: {items: @practice_data.map(&:practice).uniq.sort }) %>
<%= content_tag(:div, "", id: "pie_practice_data", data: {items: PracticeDatum.chart_data }) %>

<div id="legend" class="legend-container"> </div>

<table>
  <thead>
    <tr>
      <th>Practice</th>
      <th>Month</th>
      <th>Count</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practice_data.each do |practice_datum| %>
      <tr>
        <td><%= practice_datum.practice %></td>
        <td><%= practice_datum.month %></td>
        <td><%= practice_datum.count %></td>
        <td><%= practice_datum.value %></td>
        <td><%= link_to 'Show', practice_datum %></td>
        <td><%= link_to 'Edit', edit_practice_datum_path(practice_datum) %></td>
        <td><%= link_to 'Destroy', practice_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice datum', new_practice_datum_path %>

app/views/practice_data/new.html.erb
<h1>New practice_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', practice_data_path %>

app/views/practice_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Practice:</strong>
  <%= @practice_datum.practice %>
</p>

<p>
  <strong>Month:</strong>
  <%= @practice_datum.month %>
</p>

<p>
  <strong>Count:</strong>
  <%= @practice_datum.count %>
</p>

<p>
  <strong>Value:</strong>
  <%= @practice_datum.value %>
</p>

<%= link_to 'Edit', edit_practice_datum_path(@practice_datum) %> |
<%= link_to 'Back', practice_data_path %>

app/views/row_items/_form.html.erb
<%= form_for(@row_item) do |f| %>
  <% if @row_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@row_item.errors.count, "error") %> prohibited this row_item from being saved:</h2>

      <ul>
      <% @row_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_text %><br>
    <%= f.text_field :id_text %>
  </div>
  <div class="field">
    <%= f.label :x_data %><br>
    <%= f.text_field :x_data %>
  </div>
  <div class="field">
    <%= f.label :y_data %><br>
    <%= f.text_field :y_data %>
  </div>
  <div class="field">
    <%= f.label :z_data %><br>
    <%= f.text_field :z_data %>
  </div>
  <div class="field">
    <%= f.label :data_set_id %><br>
    <%= f.text_field :data_set_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/row_items/edit.html.erb
<h1>Editing row_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @row_item %> |
<%= link_to 'Back', row_items_path %>

app/views/row_items/index.html.erb
<h1>Listing row_items</h1>

<table>
  <thead>
    <tr>
      <th>Id text</th>
      <th>X data</th>
      <th>Y data</th>
      <th>Radius data</th>
      <th>Data set</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @row_items.each do |row_item| %>
      <tr>
        <td><%= row_item.id_text %></td>
        <td><%= row_item.x_data %></td>
        <td><%= row_item.y_data %></td>
        <td><%= row_item.z_data %></td>
        <td><%= row_item.data_set %></td>
        <td><%= link_to 'Show', row_item %></td>
        <td><%= link_to 'Edit', edit_row_item_path(row_item) %></td>
        <td><%= link_to 'Destroy', row_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Row item', new_row_item_path %>

app/views/row_items/new.html.erb
<h1>New row_item</h1>

<%= render 'form' %>

<%= link_to 'Back', row_items_path %>

app/views/row_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id text:</strong>
  <%= @row_item.id_text %>
</p>

<p>
  <strong>X data:</strong>
  <%= @row_item.x_data %>
</p>

<p>
  <strong>Y data:</strong>
  <%= @row_item.y_data %>
</p>

<p>
  <strong>Radius data:</strong>
  <%= @row_item.z_data %>
</p>

<p>
  <strong>Data set:</strong>
  <%= @row_item.data_set %>
</p>

<%= link_to 'Edit', edit_row_item_path(@row_item) %> |
<%= link_to 'Back', row_items_path %>